name: Build Docker Images

on:
  workflow_dispatch:
    inputs:
      directory:
        description: 'Directory to build Docker image'
        required: false
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Get list of Dockerfiles
        id: dockerfiles
        run: |
          if [ -z "${{ github.event.inputs.directory }}" ]; then
            files=$(find . -name 'Dockerfile')
          else
            files=${{ github.event.inputs.directory }}/Dockerfile
          fi
          echo "files=$files" >> $GITHUB_ENV

      - name: Build Docker images
        run: |
          for file in $files; do
            if [ -f "$file" ]; then
              echo "Building Docker image for $file"
              dir=$(dirname $file)
              image_name=$(basename $dir)
              docker build -t myorg/$image_name:latest $dir
            else
              echo "Dockerfile $file not found, skipping."
            fi
          done
        env:
          files: ${{ env.files }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker images
        run: |
          for file in $files; do
            if [ -f "$file" ]; then
              dir=$(dirname $file)
              image_name=$(basename $dir)
              docker push myorg/$image_name:latest
            fi
          done
        env:
          files: ${{ env.files }}
